# Generated by Django 2.2.12 on 2020-05-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200519_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='r3',
        ),
    ]
