# Generated by Django 2.2.12 on 2020-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_customtext_r3'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
