# Generated by Django 2.2.12 on 2020-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_r1'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
