# Generated by Django 2.2.12 on 2020-05-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r123',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
