# Generated by Django 2.2.12 on 2020-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customtext_r123'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
