# Generated by Django 2.2.12 on 2020-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_r5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xfff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
    ]
